import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Navbar from "./components/Navbar";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
         ${roboto.className} bg-gray-100 text-gray-800  antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
